### ISSUE TITLE
Unable to traverse sorted and filtered results as expected

### ISSUE THREAD

**Issue by cdent** [sileht/python-jsonpath-rw-ext#6]
I was working on adding jsonpath-rw-ext in gabbi (to use sorts and filters) and during my testing discovered that thigngs weren't working as expected. I want to be able to traverse a sorted or filtered result to then use those results.

So I made a [branch to demo things](https://github.com/sileht/python-jsonpath-rw-ext/compare/master...cdent:demo-bug?expand=1) but I'm not sure what the correct way things out to work.

The goal is to know how to articulate tests like this:

```yaml
    - name: test sorted list
      url: /foobar
      method: POST
      request_headers:
        content-type: application/json
      data:
          - alpha: one
            beta: horse
          - alpha: two
            beta: cow
      response_json_paths:
          $[/alpha].[0].beta: horse
          $[\alpha].[0].beta: cow

    - name: test sorted dict
      url: /foobar
      method: POST
      request_headers:
        content-type: application/json
      data:
          objects:
              - alpha: one
                beta: horse
              - alpha: two
                beta: cow
      response_json_paths:
          $.objects[/alpha].[0].beta: horse
          $.objects[\alpha].[0].beta: cow
```

Having `_iterable.SortedThis.find` be:

```python
    def find(self, datum):
        """Return sorted value of This if list or dict."""
        if isinstance(datum.value, dict) and self.expressions:
            return datum
          
        import sys
        sys.stderr.write('datam: %s\n' % datum)
        sys.stderr.write('exp: %s\n' % self.expressions)
        if isinstance(datum.value, dict) or isinstance(datum.value, list):
            key = (functools.cmp_to_key(self._compare)
                   if self.expressions else None)
            return_value = [jsonpath_rw.DatumInContext(value, context=datum)
                    for value in sorted(datum.value, key=key)]
      
            return_value = [value.value for value in return_value]
            sys.stderr.write('return: %s\n' % return_value)
            return [jsonpath_rw.DatumInContext(return_value)]
        return datum
```

gets desired results but breaks the tests here. Adjusting the tests to try and work with this breaks filter and other extensions.

From what I can tell the basic underlying bug is that the thing being returned from `find()` in the extensions is not properly structured to be used for continued processing. Making it a list containing a datum which itself has the expected values sort of does the right thing but I'm insufficiently familiar with the parse tree (at least in tonight's exploration) to know what to do. Halp!

**Comment by cdent** [comment]
Here's a simple test case in gabbi language:

```yaml
    - name: test non atomic
      POST: /foobar
      request_headers:
        content-type: application/json
      data:
          - two
          - one
      response_json_paths:
          $: ['two', 'one']
          $.`sorted`: ['one', 'two']
          $[0]: 'two'
          # Above works this fails
          $.`sorted`[0]: 'one'
```
